<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4oJnzkPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4oJnzkP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4oJnzkP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored.4AyU9kb', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::show()": the $evenement argument is type-hinted with the non-existent class or interface: "App\\Entity\\Evenement".'],
        ], [
            'evenement' => '?',
        ]);
    }
}
