<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__PPek0hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..PPek0h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..PPek0h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evenement' => ['privates', '.errored._Tgt10Q', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::edit()": the $evenement argument is type-hinted with the non-existent class or interface: "App\\Entity\\Evenement".'],
        ], [
            'entityManager' => '?',
            'evenement' => '?',
        ]);
    }
}
