<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ye7zMNHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ye7zMNH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ye7zMNH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evenement' => ['privates', '.errored.5SNim6o', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::delete()": the $evenement argument is type-hinted with the non-existent class or interface: "App\\Entity\\Evenement".'],
        ], [
            'entityManager' => '?',
            'evenement' => '?',
        ]);
    }
}
