<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rw3jxHaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rw3jxHa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rw3jxHa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'billet' => ['privates', '.errored..service_locator.rw3jxHa.App\\Entity\\Billet', NULL, 'Cannot autowire service ".service_locator.rw3jxHa": it references class "App\\Entity\\Billet" but no such service exists.'],
        ], [
            'billet' => 'App\\Entity\\Billet',
        ]);
    }
}
