<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8QoogT3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8QoogT3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8QoogT3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'typeReclamation' => ['privates', '.errored..service_locator.8QoogT3.App\\Entity\\TypeReclamation', NULL, 'Cannot autowire service ".service_locator.8QoogT3": it references class "App\\Entity\\TypeReclamation" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'typeReclamation' => 'App\\Entity\\TypeReclamation',
        ]);
    }
}
