<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JXGDIorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JXGDIor' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JXGDIor'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeReclamation' => ['privates', '.errored..service_locator.JXGDIor.App\\Entity\\TypeReclamation', NULL, 'Cannot autowire service ".service_locator.JXGDIor": it references class "App\\Entity\\TypeReclamation" but no such service exists.'],
        ], [
            'typeReclamation' => 'App\\Entity\\TypeReclamation',
        ]);
    }
}
