<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__OC5DXJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..OC5DXJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..OC5DXJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeReclamationRepository' => ['privates', 'App\\Repository\\TypeReclamationRepository', 'getTypeReclamationRepositoryService', true],
        ], [
            'typeReclamationRepository' => 'App\\Repository\\TypeReclamationRepository',
        ]);
    }
}
