<?php

namespace ContainerEicUURc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeReclamation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JXGDIor.App\Entity\TypeReclamation' shared service.
     *
     * @return \App\Entity\TypeReclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JXGDIor": it references class "App\\Entity\\TypeReclamation" but no such service exists.');
    }
}
