<?php

namespace ContainerN583W70;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBillet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rw3jxHa.App\Entity\Billet' shared service.
     *
     * @return \App\Entity\Billet
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rw3jxHa": it references class "App\\Entity\\Billet" but no such service exists.');
    }
}
