<?php

namespace ContainerN583W70;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeReclamationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8QoogT3.App\Entity\TypeReclamation' shared service.
     *
     * @return \App\Entity\TypeReclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8QoogT3": it references class "App\\Entity\\TypeReclamation" but no such service exists.');
    }
}
